### PR TITLE
Add support for Travis continuous integration

### PR DESCRIPTION
**Pull request by TrentBartlem**
See https://travis-ci.org

### CODE REVIEW

**Comment by odstderek** [comment]
Can you clean up the history on this a bit? This should really be 1 commit with a descriptive commit message.

**Comment by Regner** [comment]
What @odstderek said. For reference this is best accomplished with git's rebase command.

**Comment by TrentBartlem** [comment]
Well, that went sideways in a hurry :/

**Comment by Regner** [comment]
Hahaha all good. If you want some help there are some people with a decent level of Git experience in the #devfleet channel of the Tweetfleet Slack.

**Comment by TrentBartlem** [comment]
I'll try not to rebase from --root next time :)

**Pull request closed without merging**
